### ISSUE TITLE
Interacting with wp-config

### ISSUE THREAD

**Issue by naumanahmed19** [soderlind/vscode-remote-try-wp#1]
Hi,

I just tried this env. It's really nice and easy way to setup WordPress dev environment. Just wondering if there is anyway to interact with wp-config file to add some configurations.

Thanks

**Comment by soderlind** [comment]
You could, at https://github.com/soderlind/vscode-remote-try-wp/blob/main/.devcontainer/setup.sh#L60, use [`wp config set`](https://developer.wordpress.org/cli/commands/config/set/) to add  constants and variables to wp-config.php
